twist_mux:
  ros__parameters:
    topics:
      autonomous:
        topic: nav_vel
        timeout: 0.0
        priority: 100
      
      joy:
        topic: cmd_vel_joy
        timeout: 2.0
        priority: 120
      
      master_vel:
        topic : odom_vel
        timeout: 3.0
        priority: 130
      
    locks:
      pause_nav:
        topic: pause_nav
        timeout: 0.0
        priority: 130
